name: CI/CD pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: test-memory
    runs-on: self-hosted  # Utilisation de votre runner self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Lint PHP files
        run: |
          for my-file in $(find . -name "*.jpg"); do
            file my-file
          done
